title: A Mutable Log
description: A Mutable Log
google_analytics: UA-114405074-1
remote_theme: tewarid/slate
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-relative-links
repository: tewarid/tewarid.github.io
relative_links:
  enabled:     true
  collections: true
