title: LF Notes
description: 
google_analytics: 
remote_theme: lf-notes/midnight
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-remote-theme
repository: lf-notes/lf-notes.github.io
