title: A Mutable Log
description: A blog by Devendra Tewari
google_analytics: UA-114405074-1
remote_theme: pages-themes/midnight
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-remote-theme
repository: tewarid/tewarid.github.io
