title: A Mutable Log
description: A blog by Devendra Tewari
google_analytics: G-WDSL3QH5FY
remote_theme: tewarid/midnight
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-remote-theme
repository: tewarid/tewarid.github.io
