title: LF Notes
description: 
google_analytics: 
remote_theme: tewarid/midnight
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-remote-theme
repository: tewarid/tewarid.github.io
